import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/`;

const prod = process.argv[2] === "production";

/* ── Concatenate styles/ *.css → styles.css ──────────────────────────────── */
function buildCSS() {
	const stylesDir = join(__dirname, "styles");
	const indexFile = join(stylesDir, "_index.txt");
	const order = readFileSync(indexFile, "utf-8")
		.split(/\r?\n/)
		.map(l => l.trim())
		.filter(Boolean);

	const combined = order
		.map(name => readFileSync(join(stylesDir, name), "utf-8"))
		.join("");

	writeFileSync(join(__dirname, "styles.css"), combined);
	console.log(`styles.css  ← ${order.length} files concatenated`);
}

buildCSS();

/* ── Bundle JS ───────────────────────────────────────────────────────────── */
const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
